[tool.poetry]
name = "ndicts"
version = "0.1.0"
description = "Class to handle nested dictionaries"
authors = ["Edoardo Cicirello <e.cicirello@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ipykernel = "^6.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.1.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
